#!/bin/bash

echo "==========***************============="
echo "==========Performing OS Updates============="
echo "==========***************============="
sudo apt-get update && sudo apt-get upgrade -y && sudo apt autoremove -y && sudo apt autoclean -y
echo "==========***************============="
echo "==========OS Updates Complete============="
echo "==========***************============="
echo
cd ~/Downloads/

echo "==========***************============="
echo "==========Installing CURL============="
echo "==========***************============="
sudo apt install -y curl
echo "==========***************============="
echo "==========CURL installed============="
echo "==========***************============="
echo
echo "==========***************============="
echo "==========Installing Node.JS============="
echo "==========***************============="
curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt install nodejs -y
sudo apt install -y build-essential
echo "==========***************============="
echo "==========Node.JS installed with build tools============= $(node -v)!"
echo "==========***************============="
echo
echo "==========***************============="
echo "==========Installing Yarn============="
echo "==========***************============="
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install -y yarn
echo "==========Yarn installed with version============= $(yarn -v)!"
echo "==========***************============="
echo
echo "==========***************============="
echo "==========Installing VS Code============="
echo "==========***************============="
sudo apt update
sudo apt install software-properties-common apt-transport-https wget -y
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt update
sudo apt install -y code
echo "==========***************============="
echo "==========VS Code installed============="
echo "==========***************============="
echo
echo "==========***************============="
echo "==========Installing Git============="
echo "==========***************============="
sudo apt install -y git-all
echo "==========***************============="
echo "==========Git installed with version============= $(git --version)!"
echo "==========***************============="
echo
echo "==========***************============="
echo "==========Installing Postman============="
echo "==========***************============="
sudo curl https://gist.githubusercontent.com/SanderTheDragon/1331397932abaa1d6fbbf63baed5f043/raw/postman-deb.sh | bash -s -- -e
echo "==========***************============="
echo "==========Postman installed============="
echo "==========***************============="
echo
echo "==========***************============="
echo "==========Installing  VLC============="
echo "==========***************============="
sudo apt-get install -y vlc
echo "==========***************============="
echo "==========VLC installed============="
echo "==========***************============="
echo
echo "==========***************============="
echo "==========Installing  Docker============="
echo "==========***************============="
sudo apt-get update
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker
sudo systemctl enable docker
echo "==========***************============="
echo "==========Docker installed============="
echo "==========***************============="
echo
echo "==========***************============="
echo "==========Installing  Kubernetes============="
echo "==========***************============="
sudo apt install -y virtualbox
echo $(VBoxManage --version)
sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubectl
echo $(kubectl version --client)
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
sudo install minikube /usr/local/bin
echo $(minikube version)
echo "==========***************============="
echo "==========Kubernetes installed============="
echo "==========***************============="
echo
echo "==========***************============="
echo "==========All required packages were installed successfully!!!============="
echo "==========HaPpY CoDiNg!!!============="
echo "==========***************============="
exit 0

